from enum import Enum


class RejectionReason(str, Enum):
    CONTAINS_PAGE = "contains_page"
    CONTAINS_RUT = "contains_rut"
    CONTAINS_DATE = "contains_date"
    CONTAINS_ADDRESS = "contains_address"
    CONTAINS_PHONE = "contains_phone"
    CONTAINS_EMAIL = "contains_email"
    CONTAINS_WEB = "contains_web"
    CONTAINS_COMUNA = "contains_comuna"
    CONTAINS_CIUDAD = "contains_ciudad"
    CONTAINS_REGION = "contains_region"
    CONTAINS_MONEDA = "contains_moneda"
    CONTAINS_FIRMA = "contains_firma"
    CONTAINS_REPRESENTANTE = "contains_representante"
    CONTAINS_NOTAS = "contains_notas"
    CONTAINS_ANEXO = "contains_anexo"
    CONTAINS_INDICE = "contains_indice"
    CONTAINS_BALANCE_GENERAL = "contains_balance_general"
    CONTAINS_ESTADO_FINANCIERO = "contains_estado_financiero"
    CONTAINS_PERIODO = "contains_periodo"
    CONTAINS_HEADER = "contains_header"
    CONTAINS_FOOTER = "contains_footer"
    NAME_TOO_SHORT = "name_too_short"
    NAME_TOO_LONG = "name_too_long"
    NAME_TOO_MANY_SYMBOLS = "name_too_many_symbols"
    NAME_TOO_MANY_DIGITS = "name_too_many_digits"
    NAME_ONLY_SYMBOLS = "name_only_symbols"
    NO_MONTO = "no_monto"
    NO_CODE = "no_code"
    OUTSIDE_TABLE = "outside_table"
    OCR_LOW_CONFIDENCE = "ocr_low_confidence"
    HTML_ARTIFACT = "html_artifact"
    NOISE_LINE = "noise_line"
    KNOWN_ACCOUNT = "known_account"
    IN_DICTIONARY = "in_dictionary"
    IN_LEARNING = "in_learning"
    HAS_CODE = "has_code"
    HAS_MONTO = "has_monto"
    REASONABLE_LENGTH = "reasonable_length"
    ACCOUNT_PATTERN = "account_pattern"

    def __str__(self) -> str:
        return self.value
