version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:20"
      timezone: America/Santiago
    open-pull-requests-limit: 5
    groups:
      python-production:
        dependency-type: production
        update-types:
          - minor
          - patch
      python-development:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:40"
      timezone: America/Santiago
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
