import re

REGLAS_REGEX = [
    (r"\b(caja\s*(?:chica|pesos|d[oó]lar(?:es)?|m/?e|m/?n)?|caja\s*y\s*banco|efectivo\s*y\s*equiv\w*|valores\s+disponibles|disponible|cuenta\s*corriente\s*banco|cuenta\s*vista|dep(?:[oó]sito)?(?:\s+|/)?abono\s+bancario|vales?\s+vistas?\s+(?:no\s+retirados?|en\s+cartera)|cheques?\s+(?:caducos?|en\s+cartera|en\s+tr[aá]nsito)|operaciones?\s+en\s+tr[aá]nsito|corpbanca|security\s+d[oó]lar|bancos?(?:\s+[a-z0-9\s/().-]+)?)\b", "AC.01", 0.90),
    (r"\b(inversion(es)?\s*(corto\s*plazo|cp)|fondos?\s*mutuos?(?:\s+(?:en\s+)?(?:pesos|us\$|d[oó]lar(?:es)?))?|dep[oó]sito(s)?\s*a\s*plazo(?:\s+(?:en\s+)?(?:pesos|us\$|d[oó]lar(?:es)?))?|pacto(s)?)\b", "AC.02", 0.92),
    (r"\b(clientes?(?:\s+(?:mercado\s+nacional|nacionales?|exportaci[oó]n|netos?|facturas?|boletas?|m/?e|moneda\s+extranjera))?|deudore(s)?\s*por\s*venta|cuentas?\s*por\s*cobrar\s*(clientes?)?|provisi[oó]n\s+facturas?\s+por\s+emitir)\b", "AC.03", 0.90),
    (r"\b(?:estimaci[oó]n|provisi[oó]n|deterioro)\s+(?:deuda|deudores?|cuentas?)\s+incobrables?(?:\s*\(?edi\)?)?\b", "AC.03", 0.90),
    (r"\b(docum(en|e)?tos?\s*por\s*cobrar|letras?\s*(por|a)\s*cobrar|pagare(s)?\s*por\s*cobrar|cheques?\s*por\s*cobrar)\b", "AC.04", 0.92),
    (r"\b(inventario(s)?|existencia(s)?|mercader[ií]a(s)?|stock|materia(s)?\s*prima(s)?|productos?\s*(terminado|en\s*proceso|agr[ií]cola\s*en\s*proceso)|gastos?\s*futuras?\s*cosechas?|cosechas?\s+en\s+proceso|uvas?\s+y\s+vinos?|vinos?\s+(?:a\s+granel|embotellados?|en\s+proceso)|insumos?\s*(?:agr[ií]colas?|vitivin[ií]colas?)?|agroqu[ií]micos?\s+y\s+fertilizantes?|materiales?\s+conducci[oó]n\s+agr[ií]cola|embalajes?|activos?\s*biol[oó]gicos?)\b", "AC.05", 0.92),
    (r"\b(relacionada(s)?\s*(cp|corriente)|cuenta\s*corriente\s*relacionad|gastos?\s*por\s*recuperar\s*ee\s*rr|cuentas?\s*por\s*cobrar\s*eerr)\b", "AC.06", 0.88),
    (r"(cuenta\s+(particular|corriente)\s+(socio|accionista))|(cta\.?\s*(cte|particular)\s+(socio|accionista))|retiro(s)?\s+(de\s+)?socio|dividendo(s)?\s+(provisorio|anticipado)", "AC.06S", 0.93),
    (r"\b(iva\s*(credito|cf)|ppm|impuesto(s)?\s*por\s*recuperar(?:\s+ppua)?|ppua|anticipo(s)?\s*(a\s*)?(?:proveedor|acreedores?)|gasto(s)?\s*anticipado(s)?|deudore(s)?\s*varios|fondos?\s*por\s*rendir|anticipos?\s*(?:al\s*)?personal|cuentas?\s*(?:corrientes?|cte|ctes?|particulares?)?\s*(?:del\s*)?personal|cuentascte\s*(?:del\s*)?personal|ctas?\s*(?:ctes?|particulares?)?\s*(?:del\s*)?personal|prestamos?\s*(?:al\s*)?personal|sobregiros?\s*(?:del\s*)?personal|cta\s*pte\s*otros\s*beneficios\s*personal|asig(?:naci[oó]n)?\s+fam(?:iliar)?\s+por\s+recuperar|sence|credito\s*sence|gastos?\s*por\s*recuperar|reclamos?\s*(?:al\s*)?seguro|siniestros?\s*por\s*cobrar|donaci[oó]n|otras?\s+cuentas?\s+por\s+cobrar\s*(?:c/?p|corto\s*plazo)?)\b", "AC.07", 0.88),
    (r"\b(?:derechos?|fair\s*value|valor\s*razonable)\s*(?:en\s*)?derivados?(?:\s*\(activo\))?|derivados?\s+financieros?\s*(?:activo|cp)?|contratos?\s+forward\s*activo\b", "AC.08", 0.90),
    (r"\b(activo\s*fijo|propiedad(es)?\s*planta|maquinaria(s)?|veh[ií]culo(s)?|terreno(s)?|construccion(es)?|mueble(s)?\s*y\s*[uú]til(es)?|equipos?\s*(?:de\s*)?computacion|parronales?|vi[ñn]edos?|plantaciones?(?:\s*frutales?)?|arboledas?|pozos?\s*profundos?|salas?\s*de\s*bombas?|bocatomas?(?:,\s*piscinas?\s*y\s*canales?)?|tranques?(?:\s*(?:y\s*canales?|de\s*acumulaci[oó]n))?|galpones?|bodegas?|talleres?|taller|casas?\s*habitaci[oó]n|oficinas?|colectivos?|obras?\s+en\s+ejecuci[oó]n|obras?\s*civiles?|azufradoras?|carros?\s*cosecheros?|tractores?|implementos?\s*agr[ií]colas?|camiones?|camionetas?|motocicletas?|cuatrimotos?|furgones?|gruas?\s*horquillas?|pulverizadoras?|rastras?|arados?|utilaje\s*y\s*herramientas?|herramientas?|equipos?\s*(?:de\s*)?(?:bombeo|riego|radio|procesamiento\s*de\s*datos)|sistemas?\s*de\s*riego|packing|casino|plantas?\s*faenadoras?|instalaciones?\s*(?:el[eé]ctricas?|de\s*packing|generales?)|l[ií]neas?\s*de\s*distribuci[oó]n|campamentos?|ganado|animales?)\b", "ANC.01", 0.90),
    (r"\b(intangible(s)?|goodwill|marca(s)?|patente(s)?|licencia(s)?|software|llave\s*de\s*negocio|derechos?\s*de\s*agua(?:s)?|derechos?\s*de\s*aprovechamiento|cuotas?\s*de\s*agua)\b", "ANC.03", 0.90),
    (r"\b(inversion(es)?\s*(en\s*otras?\s*(empresas?|sociedades?)|permanente(s)?|lp|largo\s*plazo)|accione(s)?\s*en\s*sociedad|participacion(es)?\s*(en\s*)?soci)\b", "ANC.04", 0.90),
    (r"\b(relacionada(s)?\s*(lp|largo\s*plazo))\b", "ANC.05", 0.88),
    (r"\b(proveedor(es)?(?:\s+(?:uva\s+y\s+vino|insumos?|nacionales?|extranjeros?))?|acreedore(s)?\s*comercial|facturas?\s*por\s*pagar|cuentas?\s*por\s*pagar\s*proveedor|documentos?\s*por\s*pagar|doctos?\s*por\s*pagar|servicios?\s+por\s+documentar|recepciones?\s+por\s+documentar(?:\s*\(stock\))?|recepciones?\s+varias|prov(?:\.|isi[oó]n)?\s*proveedores|prov(?:\.|isi[oó]n)?\s*insumos?\s*por\s*pagar|dctos\s+y\s+ctas\s+por\s+pagar|tarjetas?\s+corporativas?\s+por\s+pagar|agencia\s+de\s+aduanas?)\b", "PC.01", 0.90),
    (r"\b(obligaciones?\s*(?:con\s*)?(?:instituciones?\s*(?:de\s*cr[eé]dito|financieras?)|financieras?|bancos?|bancarias?\s*(?:cp|corto)?)|credito(s)?\s*banc|prestamo(s)?\s*banc|linea\s*de\s*credito|sobregiro|(?:obligaci[oó]n|obifgaci[oó]n|pasivo)?\s*/?\s*fair\s*value\s*derivados|derivados?\s+financieros?\s*pasivo)\b", "PC.02", 0.88),
    (r"\bleasing\s*(cp|corriente|corto)?\b", "PC.03", 0.90),
    (r"\bfactoring\b", "PC.04", 0.94),
    (r"\b(iva\s*(?:debito|df|d\s*f)|impuesto(s)?\s*por\s*pagar|provision\s*impuesto|impuesto\s*(a\s*la\s*)?renta|primera\s*categoria|impuesto\s*unico|ppm\s*por\s*pagar|impt?o\s*por\s*pagar)\b", "PC.05", 0.88),
    (r"\b(remuneracion(es)?|sueldo(s)?|vacaciones?|provis(?:\.|i[oó]n)?\s*vacaciones?(?:\s+rol\s+(?:general|privado))?|honorario(s)?\s*por\s*pagar|gratificacion(es)?|imposicion(es)?|afp|isapre|leyes\s*sociales|finiquito(s)?|indemnizacion|ret(?:enci[oó]n)?\s*trabaj(?:adores)?\s*por\s*pagar|beneficios?\s+(?:a\s+los\s+)?empleados?|feriado\s+y\s+ot(?:ros)?\s*benef(?:icios)?)\b", "PC.06", 0.86),
    (r"\b(relacionada(s)?\s*(cp|corriente)\s*pasivo|cta\s*cte\s*socios?\s*\(?en\s*pasivo)\b", "PC.07", 0.86),
    (r"\b(anticipo(s)?\s*de\s*cliente(s)?|ingreso(s)?\s*(percibido|recibido).*(adelantado|anticipado)|otros?\s*pasivos?\s*(corrientes?|circulantes?)|provision(es)?\s*varia(s)?|acreedore(s)?\s*vario(s)?|provisi[oó]n\s*(?:marketing|comisi[oó]n|honorarios?|auditor[ií]a|directores|gastos?|existencias?))\b", "PC.08", 0.85),
    (r"\b(obligaciones?\s*bancarias?\s*(lp|largo)|credito(s)?\s*banc.*largo|prestamo(s)?\s*banc.*largo|mutuo(s)?\s*hipotecario(s)?)\b", "PNC.01", 0.88),
    (r"\bleasing\s*(lp|largo)\b", "PNC.02", 0.90),
    (r"\b(bono(s)?|debenture(s)?)\b", "PNC.03", 0.90),
    (r"\b(relacionada(s)?\s*(lp|largo)\s*pasivo)\b", "PNC.04", 0.86),
    (r"\b(indemnizacion(es)?\s*(por\s*)?a[ñn]os?\s*(de\s*)?servicio|provision(es)?\s*lp|impuesto(s)?\s*diferido(s)?\s*lp)\b", "PNC.05", 0.85),
    (r"\b(capital\s*(pagado|suscrito|social|propio)?|aporte(s)?\s*(de\s*)?(capital|socios?))\b", "PAT.01", 0.90),
    (r"\b(reserva(s)?(\s*legal)?|prima\s*de\s*emision|retasaci[oó]n\s*t[eé]cnica|revaluaci[oó]n\s*t[eé]cnica)\b", "PAT.02", 0.88),
    (r"\b(utilidad(es)?\s*(acumulada(s)?|retenida(s)?)|ganancia(s)?\s*acumulada(s)?|resultado(s)?\s*acumulado(s)?|p[eé]rdida(s)?\s*acumulada(s)?)\b", "PAT.03", 0.90),
    (r"\butilidad\s*del\s*(ejercicio|periodo|a[ñn]o)|resultado\s*del\s*(ejercicio|periodo)|p[eé]rdida\s*del\s*(ejercicio|periodo)|utilidad\s*[/(]?\s*p[eé]rdida\b", "PAT.04", 0.92),
    (r"\b(venta(s)?(?:\s+(?:tour|degustaciones?|almuerzos?|merchandising|embotellado|granel|muestras?|insumos?|embalajes?|agroqu[ií]m(?:icos)?|activo\s+fijo))?|ingreso(s)?\s*(por\s*venta|operacional|del\s*giro)|facturacion|servicios?\s+de\s+vinificaci[oó]n|prestaci[oó]n\s+de\s+servicios?)\b", "ER.01", 0.90),
    (r"\b(?:costo(s)?\s*(de\s*)?(?:venta(s)?|vta\.?|explotacion|produccion|mercader[ií]a|motos?\s*(usadas?)?|repuestos?(\s+y\s+accesorios)?|servicio\s+taller|embotellado|granel|tour|muestras?|insumos?|embalajes?|agroqu[ií]m(?:icos)?)|merma\s+proceso\s+productivo|insumos?\s+agr[ií]colas?|materiales?\s+conducci[oó]n\s+agr[ií]cola)\b", "ER.02", 0.92),
    (r"\b(gasto(s)?\s*(de\s*)?(administracion|general(es)?|gestion)|combustibles?\s*y\s*lubricantes?|energ[ií]a\s*el[eé]ctrica|suministros?|asesor[ií]as?\s*(?:t[eé]cnicas?|agron[oó]micas?|legales?|contables?)|fletes?\s*y\s*transportes?|mantenci[oó]n\s*y\s*reparaci[oó]n|seguros?\s*(?:agr[ií]colas?|generales?)|gastos?\s*de\s*viajes?|vi[aá]ticos?|patentes?\s*municipales?|contribuciones?|sueldos?\s*y\s*remuneraciones?|leyes\s*sociales\s*e\s*imposiciones?|servicios?\s*m\.?obra\s*campos?)\b", "ER.04", 0.88),
    (r"\bgasto(s)?\s*(de\s*)?(venta(s)?|comercial(es)?|marketing|distribucion)\b", "ER.05", 0.88),
    (r"\b(depreciacion|amortizacion)\b", "ER.07", 0.90),
    (r"\bgasto(s)?\s*financiero(s)?|intere(s|ses)?\s*(pagado|bancario|leasing|factoring)|comision(es)?\s*bancaria(s)?", "ER.09", 0.90),
    (r"\bimpuesto\s*(a\s*la\s*renta|primera\s*categoria)\b", "ER.10", 0.90),
    (r"\butilidad\s*neta|resultado\s*neto|net\s*income|ganancia\s*neta", "ER.11", 0.92),
    (r"\b(depreciaci[oó]n(?:es)?|amortizaci[oó]n(?:es)?|deterioro)\s+acumulad[ao]s?\b", "ANC.01.01", 0.90),
    (r"\b(?:ganancia|p[eé]rdida|resultado).*atribuible\s+a\s+los\s+propietarios.*\bcontroladora\b", "ER.20", 0.97),
    (r"\b(?:ganancia|p[eé]rdida|resultado).*atribuible\s+a\s+(?:las\s+)?participaciones\s+no\s+controladoras\b", "ER.21", 0.97),
]

REGLAS_COMPILADAS = [(re.compile(p, re.IGNORECASE | re.UNICODE), c, conf) for p, c, conf in REGLAS_REGEX]
