"""build_account_synonyms.py — Genera knowledge_base/account_synonyms.json.

Diccionario CURADO de sinónimos por cuenta del catálogo maestro (Sprint 37).
Para cada cuenta: nombre oficial, sinónimos, abreviaciones, errores OCR
frecuentes, errores de digitación y variantes comunes.

Regeneración:
    python3 tools/build_account_synonyms.py

El JSON resultante es la base de conocimiento que Sprint 38 integrará al
clasificador. Este script NO modifica ningún flujo existente.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
CATALOGO_PATH = BASE_DIR / "catalogo_maestro.json"
SALIDA_PATH = BASE_DIR / "knowledge_base" / "account_synonyms.json"


def _cargar_catalogo() -> dict:
    with open(CATALOGO_PATH, encoding="utf-8") as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Conocimiento curado (código → sinónimos)
# ---------------------------------------------------------------------------

CURADO: dict[str, dict] = {
    # ------------------------------ ACTIVOS ------------------------------ #
    "AC.01": {
        "sinonimos": [
            "caja", "caja general", "bancos", "banco", "disponibilidades",
            "caja y banco", "fondos disponibles", "dinero en caja",
            "saldo en banco", "efectivo", "efectivo y equivalentes",
        ],
        "abreviaciones": ["bco", "bcos", "caja", "c y b"],
        "errores_ocr": ["cai a", "bancos", "banco s", "caia"],
        "errores_digitacion": ["caja i banco", "cajaybancos"],
        "variantes": ["caja moneda nacional", "caja m/n", "caja moneda extranjera",
                      "banco de chile", "bancos cuentas corrientes", "caja y bancos",
                      "banco estado", "banco estado cuenta corriente"],
    },
    "AC.02": {
        "sinonimos": ["inversiones temporales", "depositos a plazo", "fondos mutuos",
                      "pactos", "inversiones financieras", "inversiones de corto plazo",
                      "instrumentos financieros", "valores negociables"],
        "abreviaciones": ["dap", "daps", "dp", "inversiones cp", "inv cp"],
        "errores_ocr": ["inversiones", "depsitos a plazo", "fondos mutos"],
        "errores_digitacion": ["inversiones corto plazo", "depositos a plazo"],
        "variantes": ["depositos a plazo corto plazo", "deposito a plazo", "pacto",
                      "fondos mutuos inversion", "inversiones de renta fija"],
    },
    "AC.03": {
        "sinonimos": ["deudores por ventas", "cuentas por cobrar clientes",
                      "deudores comerciales", "deudores por venta", "clientes",
                      "cuentas por cobrar", "clientes del exterior",
                      "clientes nacionales"],
        "abreviaciones": ["cxc", "c x c", "deud.", "dpp", "d p v", "cli"],
        "errores_ocr": ["clientes", "deudores por vta", "cxc.", "cuentas por cobrar"],
        "errores_digitacion": ["clienets", "clintes", "cuentas por cobrar clientes"],
        "variantes": ["clientes nacionales", "clientes extranjeros", "deudores por venta",
                      "deudores comerciales por venta", "cuentas por cobrar comerciales",
                      "clientes cuenta corriente", "clientes c/c", "cxc clientes"],
    },
    "AC.04": {
        "sinonimos": ["documentos por cobrar", "letras por cobrar",
                      "pagarés por cobrar", "vales por cobrar",
                      "efectos por cobrar", "documentos"],
        "abreviaciones": ["doctos por cobrar", "doc por cobrar", "doctos", "doc.",
                          "l/p", "letras"],
        "errores_ocr": ["documentos por cobrar", "doctos por cobrar", "letras por cobrar"],
        "errores_digitacion": ["documentos por cobrar", "documentos por cobrar."],
        "variantes": ["letras por cobrar", "pagarés por cobrar", "efectos por cobrar",
                      "documentos y letras por cobrar", "vales por cobrar",
                      "pagaré por cobrar", "documentos por cobrar clientes"],
    },
    "AC.05": {
        "sinonimos": ["existencias", "mercaderías", "stock", "inventario",
                      "existencias de mercaderías", "materiales", "productos",
                      "mercaderias"],
        "abreviaciones": ["exis.", "inv", "merc."],
        "errores_ocr": ["existencias", "mercaderias", "inventario"],
        "errores_digitacion": ["inventario", "existencias de mercaderia"],
        "variantes": ["existencias de mercaderías", "mercaderías", "inventario de mercaderías",
                      "existencias de materiales", "productos terminados", "materias primas",
                      "mercaderías en bodega", "stock de mercaderías"],
    },
    "AC.06": {
        "sinonimos": ["cuentas por cobrar relacionadas", "empresas relacionadas",
                      "partes relacionadas", "cuentas por cobrar a relacionadas",
                      "cuentas con relacionadas"],
        "abreviaciones": ["eerr", "e.e.r.r.", "rel.", "relac.", "cxc rel"],
        "errores_ocr": ["empresas relacionadas", "empresas relacionadas"],
        "errores_digitacion": ["empresasrelacionadas"],
        "variantes": ["cuentas por cobrar empresas relacionadas",
                      "cuentas por cobrar partes relacionadas", "prestamos a relacionadas cp",
                      "cxc relacionadas", "cuentas con empresas relacionadas"],
    },
    "AC.06S": {
        "sinonimos": ["retiros socios", "cuenta corriente socios", "anticipos socios",
                      "cuenta particular socios", "retiro de socios", "giros de socios",
                      "cuenta corriente accionistas"],
        "abreviaciones": ["cta cte socios", "cps", "cta socios", "ret. socios"],
        "errores_ocr": ["cta cte socios", "cuenta corriente socios"],
        "errores_digitacion": ["cta cte socios", "retiros socio"],
        "variantes": ["retiros de socios", "anticipo a socios", "cuenta corriente socios",
                      "cuenta particular socios", "prestamos a socios", "cta cte accionistas",
                      "cuenta corriente accionistas"],
    },
    "AC.07": {
        "sinonimos": ["cuentas por cobrar varias", "otros deudores", "deudores varios",
                      "cuentas por cobrar otras", "fondos por rendir", "anticipos",
                      "préstamos al personal", "cuentas por cobrar personal"],
        "abreviaciones": ["cxc varias", "cvpc", "otros deud.", "cpc"],
        "errores_ocr": ["cuentas por cobrar varias", "otros deudores"],
        "errores_digitacion": ["otras cuentas por cobrar", "cuentas por cobrar varios"],
        "variantes": ["fondos por rendir", "anticipos a proveedores", "prestamos a empleados",
                      "cuentas por cobrar empleados", "deudores varios", "otros deudores",
                      "cuentas por cobrar varias", "gastos pagados por anticipado"],
    },
    "AC.08": {
        "sinonimos": ["otros activos", "activos varios", "otros activos circulantes",
                      "activos de corto plazo", "otros"],
        "abreviaciones": ["oac", "otros ac"],
        "errores_ocr": ["otros activos corrientes", "otros activos"],
        "errores_digitacion": ["otros activos corriente", "otros activos circulante"],
        "variantes": ["otros activos corrientes", "otros activos", "activos varios",
                      "gastos anticipados", "impuestos por recuperar"],
    },
    "AC.09": {
        "sinonimos": ["activos biológicos", "animales", "plantaciones", "cultivos",
                      "ganado", "activos biologicos"],
        "abreviaciones": ["ab", "a.b."],
        "errores_ocr": ["activos biologicos", "activo biológico"],
        "errores_digitacion": ["activos biologicos", "activo biologico"],
        "variantes": ["activos biológicos corrientes", "animales vivos", "plantaciones",
                      "cultivos en desarrollo", "vino en proceso"],
    },
    "ANC.01": {
        "sinonimos": ["propiedad planta y equipo", "activos fijos", "bienes de uso",
                      "inmuebles maquinarias y equipos", "activo fijo",
                      "propiedades plantas y equipos"],
        "abreviaciones": ["ppye", "pp&e", "af", "afi", "ime", "imm", "act fijo"],
        "errores_ocr": ["activo fijo", "propiedad planta y equipo", "inmuebles"],
        "errores_digitacion": ["activo fijo", "propiedad planta y equipos"],
        "variantes": ["terrenos", "construcciones", "maquinarias", "equipos",
                      "vehículos", "muebles y útiles", "instalaciones", "activo fijo neto",
                      "activo fijo bruto", "inmuebles maquinarias y equipos",
                      "maquinarias y equipos", "vehiculos"],
    },
    "ANC.02": {
        "sinonimos": ["propiedades de inversion", "inversiones inmobiliarias",
                      "inmuebles de inversion", "propiedad de inversión"],
        "abreviaciones": ["p.i.", "prop inv"],
        "errores_ocr": ["propiedades de inversion", "inmuebles de inversion"],
        "errores_digitacion": ["propiedades de inversion", "propiedad de inversion"],
        "variantes": ["propiedades de inversión", "inmuebles de renta",
                      "inversiones inmobiliarias", "propiedades de renta"],
    },
    "ANC.03": {
        "sinonimos": ["intangibles", "patentes", "marcas", "derechos de agua",
                      "concesiones", "licencias", "software", "activos intangibles",
                      "derechos de llaves"],
        "abreviaciones": ["intang.", "intg", "d.a.", "dd agua"],
        "errores_ocr": ["intangibles", "patentes y marcas", "derechos de agua"],
        "errores_digitacion": ["intangibles", "activo intangibles"],
        "variantes": ["patentes y marcas", "marcas comerciales", "derechos de agua",
                      "concesiones", "licencias", "software", "derechos de llaves",
                      "activos intangibles", "desarrollo de software"],
    },
    "ANC.04": {
        "sinonimos": ["inversiones en sociedades", "inversiones en empresas relacionadas",
                      "acciones", "participaciones", "inversiones permanentes",
                      "inversiones en filiales"],
        "abreviaciones": ["inv. permanentes", "inversiones lp", "inv soc."],
        "errores_ocr": ["inversiones permanentes", "inversiones en sociedades"],
        "errores_digitacion": ["inversiones permanentes", "inversiones en sociedad"],
        "variantes": ["inversiones en empresas relacionadas", "inversiones en asociadas",
                      "inversiones en filiales", "inversiones en subsidiarias",
                      "participaciones en otras empresas", "inversiones largo plazo"],
    },
    "ANC.05": {
        "sinonimos": ["cuentas por cobrar relacionadas largo plazo",
                      "prestamos a relacionadas", "cuentas por cobrar a relacionadas lp",
                      "empresas relacionadas lp"],
        "abreviaciones": ["eerr lp", "rel. lp", "cxc rel lp"],
        "errores_ocr": ["cuentas por cobrar relacionadas largo plazo"],
        "errores_digitacion": ["relacionadas largo plazo"],
        "variantes": ["cuentas por cobrar empresas relacionadas largo plazo",
                      "préstamos a empresas relacionadas", "cuentas con relacionadas lp"],
    },
    "ANC.06": {
        "sinonimos": ["otros activos no corrientes", "otros activos largo plazo",
                      "otros activos de largo plazo", "otros activos"],
        "abreviaciones": ["oanc", "otros anc"],
        "errores_ocr": ["otros activos no corrientes"],
        "errores_digitacion": ["otros activos no corriente"],
        "variantes": ["otros activos no corrientes", "otros activos de largo plazo",
                      "activos por impuestos diferidos"],
    },
    "ANC.07": {
        "sinonimos": ["activos biológicos no corrientes", "activos biologicos lp",
                      "plantaciones de largo plazo"],
        "abreviaciones": ["ab lp", "a.b. lp"],
        "errores_ocr": ["activos biologicos no corrientes"],
        "errores_digitacion": ["activos biologicos largo plazo"],
        "variantes": ["activos biológicos no corrientes", "plantaciones de largo plazo",
                      "viñedos", "frutales"],
    },
    "ANC.08": {
        "sinonimos": ["goodwill", "plusvalía", "plusvalia comprada",
                      "diferencia positiva de combinacion de negocios"],
        "abreviaciones": ["gw", "plus."],
        "errores_ocr": ["plusvalia", "goodwill"],
        "errores_digitacion": ["plusvalia", "goodwill"],
        "variantes": ["plusvalía", "plusvalía comprada", "goodwill",
                      "diferencia de compra"],
    },
    # ------------------------------ PASIVOS ------------------------------ #
    "PC.01": {
        "sinonimos": ["cuentas por pagar proveedores", "proveedores nacionales",
                      "proveedores extranjeros", "acreedores comerciales",
                      "proveedores", "cuentas por pagar"],
        "abreviaciones": ["cxp", "c x p", "prov.", "acreed.", "proveed.", "c/p"],
        "errores_ocr": ["proveedores", "cuentas por pagar", "acreedores comerciales"],
        "errores_digitacion": ["proveedores", "cuentas por pagar proveedores"],
        "variantes": ["proveedores nacionales", "proveedores extranjeros",
                      "cuentas por pagar comerciales", "acreedores comerciales",
                      "proveedores cuenta corriente", "cxp proveedores"],
    },
    "PC.02": {
        "sinonimos": ["prestamos bancarios", "deudas bancarias", "sobregiros",
                      "lineas de credito", "obligaciones con bancos",
                      "prestamos bancarios corto plazo"],
        "abreviaciones": ["prest. banc.", "deuda bancaria", "bcp"],
        "errores_ocr": ["prestamos bancarios", "obligaciones bancarias"],
        "errores_digitacion": ["prestamos bancarios", "obligaciones bancaria"],
        "variantes": ["obligaciones con instituciones financieras", "sobregiro bancario",
                      "línea de crédito", "préstamos de bancos", "deuda bancaria cp",
                      "mutuos hipotecarios"],
    },
    "PC.03": {
        "sinonimos": ["obligaciones leasing", "leasing por pagar", "arrendamiento financiero",
                      "leasing corriente", "deuda leasing"],
        "abreviaciones": ["leasing cp", "lea.", "arriendo financiero"],
        "errores_ocr": ["leasing", "obligaciones por leasing"],
        "errores_digitacion": ["obligaciones leasing", "leasing por pagar"],
        "variantes": ["leasing corto plazo", "obligaciones por arrendamiento financiero",
                      "leasing por pagar", "deuda por leasing"],
    },
    "PC.04": {
        "sinonimos": ["factoring", "cesión de facturas", "facturas cedidas"],
        "abreviaciones": ["fact."],
        "errores_ocr": ["factoring"],
        "errores_digitacion": ["factoring"],
        "variantes": ["factoring", "cesión de cuentas por cobrar", "facturas vendidas"],
    },
    "PC.05": {
        "sinonimos": ["impuestos por pagar", "impuesto a la renta por pagar",
                      "iva por pagar", "retenciones", "pagos provisionales mensuales",
                      "impuestos retenidos", "impuestos"],
        "abreviaciones": ["imptos por pagar", "impto.", "ppm", "p.p.m.", "iva",
                          "reten.", "rtte", "rtten"],
        "errores_ocr": ["impuestos por pagar", "impuesto a la renta", "pagos provisionales"],
        "errores_digitacion": ["impuestos por pagar", "impuesto por pagar"],
        "variantes": ["impuesto a la renta por pagar", "impuesto al valor agregado por pagar",
                      "iva debito fiscal", "iva credito fiscal", "retenciones de impuestos",
                      "pagos provisionales mensuales", "impuesto unico", "p.p.m.",
                      "impuestos retenidos", "impuestos por pagar"],
    },
    "PC.06": {
        "sinonimos": ["sueldos por pagar", "remuneraciones por pagar",
                      "remuneraciones pendientes", "vacaciones por pagar",
                      "remuneraciones", "sueldos y salarios por pagar"],
        "abreviaciones": ["rem.", "rem", "sueldos", "salarios", "cta por pagar rem"],
        "errores_ocr": ["remuneraciones por pagar", "sueldos por pagar"],
        "errores_digitacion": ["remuneraciones por pagar", "remuneraciones a pagar"],
        "variantes": ["sueldos por pagar", "remuneraciones por pagar",
                      "remuneraciones pendientes de pago", "vacaciones por pagar",
                      "gratificaciones por pagar", "indemnizaciones por pagar"],
    },
    "PC.07": {
        "sinonimos": ["cuentas por pagar relacionadas", "empresas relacionadas por pagar",
                      "partes relacionadas", "cuentas con relacionadas",
                      "obligaciones con relacionadas"],
        "abreviaciones": ["eerr", "rel. cp", "cxp rel"],
        "errores_ocr": ["cuentas por pagar relacionadas"],
        "errores_digitacion": ["empresas relacionadas pasivo"],
        "variantes": ["cuentas por pagar empresas relacionadas", "mutuos relacionados",
                      "cuentas por pagar partes relacionadas", "cuentas con relacionadas cp"],
    },
    "PC.08": {
        "sinonimos": ["otros pasivos", "acreedores varios", "pasivos varios",
                      "otros pasivos corrientes", "otros"],
        "abreviaciones": ["opc", "otros pc"],
        "errores_ocr": ["otros pasivos corrientes"],
        "errores_digitacion": ["otros pasivos corriente"],
        "variantes": ["acreedores varios", "otros pasivos corrientes", "pasivos varios",
                      "dividendos por pagar", "otros pasivos de corto plazo"],
    },
    "PNC.01": {
        "sinonimos": ["prestamos bancarios largo plazo", "deudas bancarias largo plazo",
                      "obligaciones bancarias", "deuda financiera largo plazo",
                      "mutuos hipotecarios"],
        "abreviaciones": ["deuda bancaria lp", "bancos lp", "pblp"],
        "errores_ocr": ["obligaciones bancarias largo plazo"],
        "errores_digitacion": ["prestamos bancarios largo plazo"],
        "variantes": ["obligaciones con instituciones financieras largo plazo",
                      "préstamos bancarios de largo plazo", "deuda financiera lp"],
    },
    "PNC.02": {
        "sinonimos": ["leasing largo plazo", "obligaciones leasing largo plazo",
                      "arrendamiento financiero largo plazo", "leasing no corriente"],
        "abreviaciones": ["leasing lp", "lea. lp"],
        "errores_ocr": ["leasing largo plazo"],
        "errores_digitacion": ["leasing largo plazo"],
        "variantes": ["leasing no corriente", "obligaciones por leasing largo plazo"],
    },
    "PNC.03": {
        "sinonimos": ["obligaciones por bonos", "bonos emitidos", "deuda de bonos",
                      "bonos por pagar"],
        "abreviaciones": ["bonos", "oblig. bonos"],
        "errores_ocr": ["bonos por pagar", "obligaciones por bonos"],
        "errores_digitacion": ["bonos por pagar"],
        "variantes": ["bonos emitidos", "obligaciones por bonos", "deuda de bonos"],
    },
    "PNC.04": {
        "sinonimos": ["cuentas por pagar relacionadas largo plazo",
                      "obligaciones con relacionadas largo plazo", "empresas relacionadas lp"],
        "abreviaciones": ["rel. lp", "cxp rel lp", "eerr lp"],
        "errores_ocr": ["cuentas por pagar relacionadas largo plazo"],
        "errores_digitacion": ["relacionadas largo plazo pasivo"],
        "variantes": ["cuentas por pagar empresas relacionadas largo plazo",
                      "mutuos con relacionadas lp", "obligaciones con relacionadas lp"],
    },
    "PNC.05": {
        "sinonimos": ["otros pasivos no corrientes", "otros pasivos largo plazo",
                      "otros pasivos de largo plazo"],
        "abreviaciones": ["opnc", "otros pnc"],
        "errores_ocr": ["otros pasivos no corrientes"],
        "errores_digitacion": ["otros pasivos no corriente"],
        "variantes": ["pasivos por impuestos diferidos", "otros pasivos no corrientes",
                      "otros pasivos de largo plazo", "provisiones de largo plazo"],
    },
    # ---------------------------- PATRIMONIO ----------------------------- #
    "PAT.01": {
        "sinonimos": ["capital pagado", "capital social", "capital suscrito y pagado",
                      "capital", "aporte de capital"],
        "abreviaciones": ["cap.", "cap pag", "cap social"],
        "errores_ocr": ["capital pagado", "capital social"],
        "errores_digitacion": ["capital pagado", "capital social"],
        "variantes": ["capital suscrito y pagado", "capital pagado", "capital social",
                      "aportes de capital", "capital inicial"],
    },
    "PAT.02": {
        "sinonimos": ["reservas legales", "reservas de capital", "reservas estatutarias",
                      "reservas", "reservas de utilidades"],
        "abreviaciones": ["res.", "reservas legales", "rev."],
        "errores_ocr": ["reservas", "reservas legales"],
        "errores_digitacion": ["reservas", "reservas legal"],
        "variantes": ["reservas legales", "reservas de capital", "reservas estatutarias",
                      "reservas de utilidades", "reserva legal"],
    },
    "PAT.03": {
        "sinonimos": ["utilidades acumuladas", "utilidades no distribuidas",
                      "resultados acumulados", "utilidades retenidas",
                      "utilidades de ejercicios anteriores"],
        "abreviaciones": ["util. acum.", "uai", "result. acum.", "ur"],
        "errores_ocr": ["utilidades retenidas", "utilidades acumuladas"],
        "errores_digitacion": ["utilidades retenidas", "utilidad retenida"],
        "variantes": ["utilidades acumuladas", "utilidades retenidas",
                      "utilidades no distribuidas", "resultados acumulados",
                      "utilidades de ejercicios anteriores", "utilidad acumulada"],
    },
    "PAT.04": {
        "sinonimos": ["resultado del periodo", "utilidad del ejercicio",
                      "pérdida del ejercicio", "ganancia del ejercicio",
                      "resultado neto", "resultado del ejercicio"],
        "abreviaciones": ["rdc", "result. ej.", "util. ej."],
        "errores_ocr": ["resultado del ejercicio", "utilidad del ejercicio"],
        "errores_digitacion": ["resultado del ejercicio", "resultado ejercicio"],
        "variantes": ["resultado del período", "utilidad del ejercicio",
                      "pérdida del ejercicio", "ganancia del ejercicio",
                      "resultado neto del ejercicio", "utilidad o pérdida del ejercicio"],
    },
    "PAT.05": {
        "sinonimos": ["participación no controladora", "participacion no controladora",
                      "minoritarios", "interes minoritario", "participacion minoritaria"],
        "abreviaciones": ["pnc", "p.n.c.", "min."],
        "errores_ocr": ["participacion no controladora", "participacion minoritaria"],
        "errores_digitacion": ["participacion no controladora", "interes minoritario"],
        "variantes": ["participación no controladora", "interés minoritario",
                      "participación de minoritarios", "intereses minoritarios"],
    },
    "PAT.06": {
        "sinonimos": ["capital suscrito y pagado", "capital suscrito",
                      "capital social suscrito"],
        "abreviaciones": ["cap. susc.", "cs"],
        "errores_ocr": ["capital suscrito"],
        "errores_digitacion": ["capital suscrito", "capital suscrito y pagado"],
        "variantes": ["capital suscrito y pagado", "capital suscrito",
                      "capital emitido"],
    },
    "PAT.07": {
        "sinonimos": ["capital no pagado", "capital pendiente de enterar",
                      "capital por enterar"],
        "abreviaciones": ["cap. por enterar"],
        "errores_ocr": ["capital por enterar"],
        "errores_digitacion": ["capital por enterar", "capital por enterrar"],
        "variantes": ["capital por enterar", "capital no enterado", "capital pendiente"],
    },
    "PAT.08": {
        "sinonimos": ["reserva técnica revalorización activo fijo",
                      "revalorizacion del activo fijo", "reserva de revalorizacion",
                      "revalorizaciones"],
        "abreviaciones": ["rtr", "res. reval.", "reval."],
        "errores_ocr": ["reserva tecnica revalorizacion", "revalorizacion activo fijo"],
        "errores_digitacion": ["reserva revalorizacion activo fijo"],
        "variantes": ["reserva técnica revalorización activo fijo", "revalorización del activo fijo",
                      "reserva revalorización", "revalorización activo fijo"],
    },
    "PAT.09": {
        "sinonimos": ["utilidades acumuladas de ejercicios anteriores",
                      "resultados acumulados anteriores", "utilidades retenidas anteriores",
                      "utilidades de ejercicios anteriores"],
        "abreviaciones": ["u.e.a.", "uea"],
        "errores_ocr": ["utilidades de ejercicios anteriores"],
        "errores_digitacion": ["utilidades ejercicios anteriores"],
        "variantes": ["utilidades de ejercicios anteriores", "utilidades acumuladas",
                      "resultados de ejercicios anteriores", "utilidades retenidas anteriores"],
    },
    "PAT.10": {
        "sinonimos": [
            "cuenta corriente socio", "cta corriente socio", "cuenta socio",
            "prestamo socio", "prestamos socios", "prestamo a socios",
            "prestamos a socios", "cxc socio", "cxc accionista",
            "cuenta corriente accionista", "cuenta particular accionista",
            "anticipo socio", "retiro socio", "retiros", "giros socios",
            "cuenta corriente socios", "cuenta particular", "cuenta particular socios",
            "retiros de socios", "anticipos a socios", "préstamos a accionistas",
            "cuenta corriente de socios", "cuenta particular de socios",
            "socios cuenta corriente", "socio cuenta particular", "pacto socios",
        ],
        "abreviaciones": ["cps", "cta pte", "cta. pte.", "cta pte socios", "c/c socio",
                          "cta cte socio", "c.t.c. socio", "cps socios"],
        "errores_ocr": ["cta cte socio", "cuenta corriente socio", "cps",
                        "cuenta particular socio", "cta particular socios"],
        "errores_digitacion": ["cuenta particular socio", "cta particular socios",
                               "cuenta corriente socio", "prestamos a socio",
                               "retiros de socio"],
        "variantes": [
            "cuenta corriente socios", "cuenta particular socios", "cuenta corriente accionistas",
            "cuenta particular accionistas", "prestamos a socios", "prestamos a accionistas",
            "anticipos a socios", "retiros de socios", "retiros de accionistas",
            "giros de socios", "préstamos socios", "préstamos accionistas", "cuenta socios",
            "cuenta accionistas", "cuenta particular", "cuenta corriente socio",
            "cxc socios", "cxc accionistas",
        ],
    },
    "PAT.11": {
        "sinonimos": ["interes minoritario", "interes no controlador",
                      "participacion minoritaria", "participacion no controladora"],
        "abreviaciones": ["int. min.", "minorit."],
        "errores_ocr": ["interes minoritario"],
        "errores_digitacion": ["interes minoritario", "interes minoritarios"],
        "variantes": ["interés minoritario", "intereses minoritarios", "minoritarios"],
    },
    # ----------------------------- RESULTADOS ---------------------------- #
    "ER.01": {
        "sinonimos": ["ingresos por ventas", "ingresos de explotación",
                      "ventas del giro", "ingresos operacionales", "ventas netas",
                      "ventas", "ingresos ordinarios"],
        "abreviaciones": ["vts.", "vtas", "ventas", "ing. expl.", "v/n"],
        "errores_ocr": ["ventas", "ingresos por ventas", "ventas del giro"],
        "errores_digitacion": ["ventas", "ingresos por venta"],
        "variantes": ["ventas netas", "ventas del giro", "ingresos por ventas",
                      "ingresos de explotación", "ingresos operacionales",
                      "ingresos por ventas y servicios", "ventas de mercaderías"],
    },
    "ER.02": {
        "sinonimos": ["costo de venta", "costo de mercaderías", "costo de explotación",
                      "costo por ventas", "costo de ventas"],
        "abreviaciones": ["cmv", "c.v.", "costo vta", "cost. ventas"],
        "errores_ocr": ["costo de ventas", "costo de mercaderias"],
        "errores_digitacion": ["costo de venta", "costo de ventas"],
        "variantes": ["costo de venta", "costo de mercaderías", "costo de explotación",
                      "costo de ventas", "costo de producción vendida"],
    },
    "ER.03": {
        "sinonimos": ["margen bruto", "resultado bruto", "ganancia bruta"],
        "abreviaciones": ["mg", "m.b."],
        "errores_ocr": ["margen bruto"],
        "errores_digitacion": ["margen bruto", "margen bruta"],
        "variantes": ["margen bruto", "resultado bruto", "ganancia bruta"],
    },
    "ER.04": {
        "sinonimos": ["gastos administrativos", "gastos generales y de administración",
                      "gastos de administración", "gastos de administracion y ventas",
                      "gastos generales"],
        "abreviaciones": ["ggya", "g.a.", "gav", "ggaa", "adm."],
        "errores_ocr": ["gastos de administracion", "gastos generales"],
        "errores_digitacion": ["gastos de administracion", "gastos administrativos"],
        "variantes": ["gastos de administración y ventas", "gastos generales y de administración",
                      "gastos administrativos", "gastos de administración",
                      "gastos de oficina", "gastos generales"],
    },
    "ER.05": {
        "sinonimos": ["gastos de comercialización", "gastos de ventas",
                      "gastos de venta", "gastos de distribución"],
        "abreviaciones": ["g.v.", "gastos vta", "gvtas"],
        "errores_ocr": ["gastos de venta", "gastos de ventas"],
        "errores_digitacion": ["gastos de ventas", "gastos de venta"],
        "variantes": ["gastos de venta", "gastos de comercialización",
                      "gastos de distribución", "gastos de marketing"],
    },
    "ER.06": {
        "sinonimos": ["ebitda", "resultado antes de depreciación e intereses",
                      "utilidad antes de intereses impuestos depreciación y amortización"],
        "abreviaciones": ["ebitda", "e.b.i.t.d.a."],
        "errores_ocr": ["ebitda", "ebitda ajustado"],
        "errores_digitacion": ["ebitda", "ebita"],
        "variantes": ["ebitda", "ebitda ajustado", "resultado antes de depreciación e intereses"],
    },
    "ER.07": {
        "sinonimos": ["depreciación", "amortización", "depreciación del ejercicio",
                      "amortización del ejercicio", "depreciación y amortización",
                      "gasto por depreciacion", "gasto por amortizacion"],
        "abreviaciones": ["dep.", "amort.", "dep y amort", "d y a", "da", "dep ac"],
        "errores_ocr": ["depreciacion", "amortizacion", "dep y amort"],
        "errores_digitacion": ["depreciacion", "amortizacion", "depreciacion y amortizacion"],
        "variantes": ["depreciación", "amortización", "depreciación y amortización",
                      "gasto por depreciación", "gasto por amortización",
                      "depreciación del ejercicio", "amortización del ejercicio"],
    },
    "ER.08": {
        "sinonimos": ["resultado operativo", "utilidad operacional",
                      "resultado de operación", "resultado operacional"],
        "abreviaciones": ["ro", "r.o.", "ebit", "uii"],
        "errores_ocr": ["resultado operacional", "resultado operativo"],
        "errores_digitacion": ["resultado operacional", "resultado operativo"],
        "variantes": ["resultado operacional", "utilidad operacional", "ebit",
                      "resultado de explotación", "resultado operativo"],
    },
    "ER.09": {
        "sinonimos": ["intereses", "gastos bancarios", "comisiones financieras",
                      "gastos por intereses", "costos financieros",
                      "gastos financieros"],
        "abreviaciones": ["g.f.", "gastos fin.", "inter.", "int."],
        "errores_ocr": ["gastos financieros", "gastos financiero"],
        "errores_digitacion": ["gastos financieros", "gastos financieras"],
        "variantes": ["gastos por intereses", "intereses pagados",
                      "gastos bancarios", "comisiones bancarias",
                      "gastos financieros", "costos financieros"],
    },
    "ER.10": {
        "sinonimos": ["impuesto a la renta", "impuesto sobre la renta",
                      "impuesto renta", "impuesto único", "provisión impuesto a la renta"],
        "abreviaciones": ["i.r.", "irt", "impto renta", "imp. renta"],
        "errores_ocr": ["impuesto a la renta", "impuesto renta"],
        "errores_digitacion": ["impuesto a la renta", "impuesto a la renta"],
        "variantes": ["impuesto a la renta", "provisión impuesto a la renta",
                      "impuesto único a las empresas", "impuesto de primera categoría"],
    },
    "ER.11": {
        "sinonimos": ["resultado del ejercicio", "utilidad del ejercicio",
                      "ganancia neta", "resultado neto", "utilidad neta"],
        "abreviaciones": ["un", "u.n.", "rdc", "result. neto"],
        "errores_ocr": ["utilidad neta", "resultado del ejercicio"],
        "errores_digitacion": ["utilidad neta", "resultado neto"],
        "variantes": ["utilidad neta", "resultado del ejercicio", "ganancia neta",
                      "resultado neto del ejercicio", "utilidad líquida"],
    },
    "ER.12": {
        "sinonimos": ["ingresos por intereses", "productos financieros",
                      "ingresos financieros", "intereses ganados"],
        "abreviaciones": ["ing. fin.", "i.f."],
        "errores_ocr": ["ingresos financieros", "intereses ganados"],
        "errores_digitacion": ["ingresos financieros", "ingresos por intereses"],
        "variantes": ["ingresos por intereses", "intereses ganados",
                      "productos financieros", "ingresos financieros"],
    },
    "ER.13": {
        "sinonimos": ["otros ingresos y egresos", "otras ganancias",
                      "otras pérdidas", "resultado no operacional",
                      "otras ganancias y perdidas"],
        "abreviaciones": ["o.g.y.p.", "ogyp", "rno"],
        "errores_ocr": ["otras ganancias y perdidas", "resultado no operacional"],
        "errores_digitacion": ["otras ganancias y perdidas", "otras ganancias y perdidas"],
        "variantes": ["otras ganancias y pérdidas", "resultado no operacional",
                      "otros ingresos y egresos", "ganancias y pérdidas varias"],
    },
    "ER.14": {
        "sinonimos": ["corrección monetaria", "reajustes", "corrección monetaria y reajustes",
                      "diferencia por reajuste"],
        "abreviaciones": ["c.m.", "corr. mon.", "reaj."],
        "errores_ocr": ["correccion monetaria", "reajustes"],
        "errores_digitacion": ["correccion monetaria", "correccion monetaria y reajustes"],
        "variantes": ["corrección monetaria", "corrección monetaria y reajustes",
                      "reajustes", "corrección monetaria del ejercicio"],
    },
    "ER.15": {
        "sinonimos": ["diferencia de cambio", "reajuste de tipo de cambio",
                      "resultados por diferencia de cambio", "diferencias de cambio"],
        "abreviaciones": ["d.c.", "dif. cambio", "dcc"],
        "errores_ocr": ["diferencia de cambio", "diferencias de cambio"],
        "errores_digitacion": ["diferencia de cambio", "diferencias de cambio"],
        "variantes": ["diferencia de cambio", "diferencias de cambio",
                      "resultado por diferencia de cambio", "reajuste de moneda extranjera"],
    },
    "ER.16": {
        "sinonimos": ["utilidad empresas relacionadas", "resultado empresas relacionadas",
                      "ingresos por metodo de participacion", "resultados en empresas relacionadas",
                      "resultado metodo participacion"],
        "abreviaciones": ["m.p.", "eerr", "uer"],
        "errores_ocr": ["resultado metodo de participacion", "utilidad empresas relacionadas"],
        "errores_digitacion": ["resultado metodo participacion"],
        "variantes": ["utilidad de empresas relacionadas", "resultado por método de participación",
                      "ingresos de empresas relacionadas", "participación en resultados de asociadas"],
    },
    "ER.17": {
        "sinonimos": ["otros ingresos", "otros ingresos operacionales",
                      "ingresos diversos", "otros ingresos del giro"],
        "abreviaciones": ["o.i.", "otros ing."],
        "errores_ocr": ["otros ingresos", "ingresos diversos"],
        "errores_digitacion": ["otros ingresos", "otras ingresos"],
        "variantes": ["otros ingresos", "otros ingresos operacionales",
                      "ingresos diversos", "otros ingresos de explotación"],
    },
    "ER.18": {
        "sinonimos": ["otros egresos", "otras pérdidas", "egresos diversos",
                      "otros egresos del giro"],
        "abreviaciones": ["o.e.", "otros eg."],
        "errores_ocr": ["otros egresos", "egresos diversos"],
        "errores_digitacion": ["otros egresos", "otras egresos"],
        "variantes": ["otros egresos", "otras pérdidas", "egresos diversos",
                      "otros gastos"],
    },
    "ER.19": {
        "sinonimos": ["resultado antes de impuesto", "utilidad antes de impuestos",
                      "resultado pre impuesto", "resultado antes de impuestos"],
        "abreviaciones": ["raii", "r.a.i.", "uai"],
        "errores_ocr": ["resultado antes de impuestos", "utilidad antes de impuestos"],
        "errores_digitacion": ["resultado antes de impuestos", "resultado antes impuestos"],
        "variantes": ["resultado antes de impuestos", "utilidad antes de impuestos",
                      "resultado antes de impuesto a la renta", "resultado pre impuesto"],
    },
}


def main() -> int:
    catalogo = _cargar_catalogo()
    doc = {
        "version": "1.0",
        "generado_por": "tools/build_account_synonyms.py",
        "n_cuentas": len(CURADO),
        "fuente": "catalogo_maestro.json",
        "cuentas": {},
    }
    faltantes = [c for c in catalogo if c not in CURADO]
    if faltantes:
        print(f"ADVERTENCIA: cuentas sin sinónimos curados: {faltantes}", file=sys.stderr)
    for codigo, entrada in catalogo.items():
        curado = CURADO.get(codigo, {})
        doc["cuentas"][codigo] = {
            "codigo": codigo,
            "nombre_oficial": entrada.get("nombre_estandar", ""),
            "categoria": entrada.get("categoria", ""),
            "grupo_presentacion": entrada.get("grupo_presentacion", ""),
            "clasificable": entrada.get("clasificable", True),
            "sinonimos": curado.get("sinonimos", []),
            "abreviaciones": curado.get("abreviaciones", []),
            "errores_ocr": curado.get("errores_ocr", []),
            "errores_digitacion": curado.get("errores_digitacion", []),
            "variantes": curado.get("variantes", []),
        }
    SALIDA_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(SALIDA_PATH, "w", encoding="utf-8") as f:
        json.dump(doc, f, ensure_ascii=False, indent=2)
    print(f"OK: {SALIDA_PATH} ({len(doc['cuentas'])} cuentas)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
